#!/bin/bash
set -ex

# Close open System Settings windows so they're not overwritten
osascript <<EOF
set isRunning to false

-- Check if System Settings is in the process list
tell application "System Events"
    if exists (processes where name is "System Settings") then
        set isRunning to true
    end if
end tell

-- Quit the app if it's running
if isRunning then
    tell application "System Settings" to quit
end if
EOF

# Ask for the administrator password upfront
sudo -v

# Set the computer name
sudo scutil --set ComputerName "{{ .computerName }}"
sudo scutil --set HostName "{{ .computerName }}"
sudo scutil --set LocalHostName "{{ .computerName }}"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "{{ .computerName }}"

# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "

# Disable font smoothing
defaults -currentHost write -g AppleFontSmoothing -int 0

# Increase window resize speed for Cocoa applications
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Expand print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# Save to disk (not to iCloud) by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# Disable the “Are you sure you want to open this application?” dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Reveal IP address, hostname, OS version, etc. when clicking the clock in the login window
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

# Disable automatic capitalization as it’s annoying when typing code
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

# Disable smart dashes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# Disable automatic period substitution as it’s annoying when typing code
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

# Disable smart quotes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

# Trackpad: map bottom right corner to right-click
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true

# Trackpad: Increase tracking speed
defaults -currentHost write NSGLobalDomain com.apple.trackpad.scaling -float 3.0

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10

# Set language and text formats
defaults write NSGlobalDomain AppleLanguages -array "en" "nl"
defaults write NSGlobalDomain AppleLocale -string "en_GB@currency=GBP"
defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"
defaults write NSGlobalDomain AppleMetricUnits -bool true

# Set the timezone
sudo systemsetup -settimezone "Europe/London" > /dev/null

# Finder: disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true

# Finder: show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Use list view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `clmv`, `glyv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Disable the warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

# Makes Finder sort folders before files
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# Expand the following File Info panes:
# “General”, “Open with”, and “Sharing & Permissions”
defaults write com.apple.finder FXInfoPanesExpanded -dict \
	General -bool true \
	OpenWith -bool true \
	Privileges -bool true

# Dock

# Set the icon size of Dock items to 40 pixels
defaults write com.apple.dock tilesize -int 40

# Show indicator lights for open applications in the Dock
defaults write com.apple.dock show-process-indicators -bool true

# Wipe all (default) app icons from the Dock
# This is only really useful when setting up a new Mac, or if you don’t use
# the Dock to launch apps.
defaults write com.apple.dock persistent-apps -array

# Disable Dashboard
defaults write com.apple.dashboard mcx-disabled -bool true

# Don’t show Dashboard as a Space
defaults write com.apple.dock dashboard-in-overlay -bool true

# Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# Remove the auto-hiding Dock delay
defaults write com.apple.dock autohide-delay -float 0
# Remove the animation when hiding/showing the Dock
defaults write com.apple.dock autohide-time-modifier -float 0

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Make Dock icons of hidden applications translucent
defaults write com.apple.dock showhidden -bool true

# Disable the Launchpad gesture (pinch with thumb and three fingers)
defaults write com.apple.dock showLaunchpadGestureEnabled -int 0

###############################################################################
# Safari & WebKit                                                             #
###############################################################################

# Privacy: don’t send search queries to Apple
defaults write com.apple.Safari UniversalSearchEnabled -bool false
defaults write com.apple.Safari SuppressSearchSuggestions -bool true

# Show the full URL in the address bar (note: this still hides the scheme)
defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true

# Set Safari’s home page to `about:blank` for faster loading
defaults write com.apple.Safari HomePage -string "about:blank"

# Show Safari’s bookmarks bar by default
defaults write com.apple.Safari ShowFavoritesBar -bool true

# Remove useless icons from Safari’s bookmarks bar
defaults write com.apple.Safari ProxiesInBookmarksBar "()"

# Enable the Develop menu and the Web Inspector in Safari
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true

# Add a context menu item for showing the Web Inspector in web views
defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

# Enable continuous spellchecking
defaults write com.apple.Safari WebContinuousSpellCheckingEnabled -bool true
# Disable auto-correct
defaults write com.apple.Safari WebAutomaticSpellingCorrectionEnabled -bool false

# Disable AutoFill
defaults write com.apple.Safari AutoFillFromAddressBook -bool false
defaults write com.apple.Safari AutoFillPasswords -bool false
defaults write com.apple.Safari AutoFillCreditCardData -bool false
defaults write com.apple.Safari AutoFillMiscellaneousForms -bool false

# Warn about fraudulent websites
defaults write com.apple.Safari WarnAboutFraudulentWebsites -bool true

# Disable plug-ins
defaults write com.apple.Safari WebKitPluginsEnabled -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2PluginsEnabled -bool false

# Disable Java
defaults write com.apple.Safari WebKitJavaEnabled -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabled -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabledForLocalFiles -bool false

# Block pop-up windows
defaults write com.apple.Safari WebKitJavaScriptCanOpenWindowsAutomatically -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaScriptCanOpenWindowsAutomatically -bool false

# Disable auto-playing video
defaults write com.apple.Safari WebKitMediaPlaybackAllowsInline -bool false
defaults write com.apple.SafariTechnologyPreview WebKitMediaPlaybackAllowsInline -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2AllowsInlineMediaPlayback -bool false
defaults write com.apple.SafariTechnologyPreview com.apple.Safari.ContentPageGroupIdentifier.WebKit2AllowsInlineMediaPlayback -bool false

# Enable “Do Not Track”
defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true

# Update extensions automatically
defaults write com.apple.Safari InstallExtensionUpdatesAutomatically -bool true

# Activity Monitor

# Show the main window when launching Activity Monitor
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

# Visualize CPU usage in the Activity Monitor Dock icon
defaults write com.apple.ActivityMonitor IconType -int 5

# Show all processes in Activity Monitor
defaults write com.apple.ActivityMonitor ShowCategory -int 0

# Sort Activity Monitor results by CPU usage
defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
defaults write com.apple.ActivityMonitor SortDirection -int 0

# Mac App Store

# Enable the automatic update check
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

# Check for software updates daily, not just once per week
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Download newly available updates in background
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

# Install System data files & security updates
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1

# Automatically download apps purchased on other Macs
defaults write com.apple.SoftwareUpdate ConfigDataInstall -int 1

# Turn on app auto-update
defaults write com.apple.commerce AutoUpdate -bool true

# Allow the App Store to reboot machine on macOS updates
defaults write com.apple.commerce AutoUpdateRestartRequired -bool true

# Chrome


# Disable the all too sensitive backswipe on trackpads
defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool false
defaults write com.google.Chrome.canary AppleEnableSwipeNavigateWithScrolls -bool false

# Disable the all too sensitive backswipe on Magic Mouse
defaults write com.google.Chrome AppleEnableMouseSwipeNavigateWithScrolls -bool false
defaults write com.google.Chrome.canary AppleEnableMouseSwipeNavigateWithScrolls -bool false

# Use the system-native print preview dialog
defaults write com.google.Chrome DisablePrintPreview -bool true
defaults write com.google.Chrome.canary DisablePrintPreview -bool true

# Expand the print dialog by default
defaults write com.google.Chrome PMPrintingExpandedStateForPrint2 -bool true
defaults write com.google.Chrome.canary PMPrintingExpandedStateForPrint2 -bool true

# Power

# Restart automatically on power loss
sudo pmset -a autorestart 1

# Restart automatically if the computer freezes
sudo systemsetup -setrestartfreeze on

# Finder
echo "Setting Finder Preferences..."

# Show all files
defaults write com.apple.finder AppleShowAllFiles YES

# Makes new Finder windows open in the home directory
defaults write com.apple.finder NewWindowTarget PfHm

# Open many types of files with Zed
duti -s dev.zed.Zed public.json all
duti -s dev.zed.Zed public.plain-text all
duti -s dev.zed.Zed public.python-script all
duti -s dev.zed.Zed public.shell-script all
duti -s dev.zed.Zed public.source-code all
duti -s dev.zed.Zed public.text all
duti -s dev.zed.Zed public.unix-executable all
duti -s dev.zed.Zed public.data all
duti -s dev.zed.Zed .c all
duti -s dev.zed.Zed .cpp all
duti -s dev.zed.Zed .cs all
duti -s dev.zed.Zed .css all
duti -s dev.zed.Zed .go all
duti -s dev.zed.Zed .java all
duti -s dev.zed.Zed .js all
duti -s dev.zed.Zed .sass all
duti -s dev.zed.Zed .scss all
duti -s dev.zed.Zed .less all
duti -s dev.zed.Zed .vue all
duti -s dev.zed.Zed .cfg all
duti -s dev.zed.Zed .json all
duti -s dev.zed.Zed .jsx all
duti -s dev.zed.Zed .log all
duti -s dev.zed.Zed .lua all
duti -s dev.zed.Zed .md all
duti -s dev.zed.Zed .php all
duti -s dev.zed.Zed .pl all
duti -s dev.zed.Zed .py all
duti -s dev.zed.Zed .rb all
duti -s dev.zed.Zed .ts all
duti -s dev.zed.Zed .tsx all
duti -s dev.zed.Zed .txt all
duti -s dev.zed.Zed .conf all
duti -s dev.zed.Zed .yaml all
duti -s dev.zed.Zed .yml all
duti -s dev.zed.Zed .toml all

# Make it harder to quit some apps
# Safari
/usr/libexec/PlistBuddy ~/Library/Containers/com.apple.Safari/Data/Library/Preferences/com.apple.Safari.plist -c "Delete NSUserKeyEquivalents:Quit\ Safari" || true
/usr/libexec/PlistBuddy ~/Library/Containers/com.apple.Safari/Data/Library/Preferences/com.apple.Safari.plist -c "Add NSUserKeyEquivalents:Quit\ Safari string @~q"
/usr/libexec/PlistBuddy ~/Library/Containers/com.apple.Safari/Data/Library/Preferences/com.apple.Safari.plist -c "Delete NSUserKeyEquivalents:Close\ Tab" || true
/usr/libexec/PlistBuddy ~/Library/Containers/com.apple.Safari/Data/Library/Preferences/com.apple.Safari.plist -c "Add NSUserKeyEquivalents:Close\ Tab string @w"

# Zed
if ! defaults read dev.zed.Zed >/dev/null 2>&1; then
  /usr/libexec/PlistBuddy ~/Library/Preferences/dev.zed.Zed.plist -c "Delete :NSUserKeyEquivalents:Quit" || true
  /usr/libexec/PlistBuddy ~/Library/Preferences/dev.zed.Zed.plist -c "Add :NSUserKeyEquivalents:Quit string @~q"
fi

# 1Password
if ! defaults read com.1password.1password >/dev/null 2>&1; then
  /usr/libexec/PlistBuddy ~/Library/Preferences/com.1password.1password.plist -c "Delete NSUserKeyEquivalents:Quit\ 1Password" || true
  /usr/libexec/PlistBuddy ~/Library/Preferences/com.1password.1password.plist -c "Add NSUserKeyEquivalents:Quit\ 1Password string @~q"
fi

# Finder
/usr/libexec/plistbuddy -c "Set :DesktopViewSettings:GroupBy Kind" ~/Library/preferences/com.apple.finder.plist
/usr/libexec/plistbuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy kind" ~/Library/preferences/com.apple.finder.plist
/usr/libexec/plistbuddy -c "Set :DesktopViewSettings:IconViewSettings:labelOnBottom true" ~/Library/preferences/com.apple.finder.plist
/usr/libexec/plistbuddy -c "Set :DesktopViewSettings:IconViewSettings:showIconPreview true" ~/Library/preferences/com.apple.finder.plist
/usr/libexec/plistbuddy -c "Set :DesktopViewSettings:IconViewSettings:textSize 13" ~/Library/preferences/com.apple.finder.plist
/usr/libexec/plistbuddy -c "Set :DesktopViewSettings:IconViewSettings:iconSize 76" ~/Library/preferences/com.apple.finder.plist
/usr/libexec/plistbuddy -c "Set :DesktopViewSettings:IconViewSettings:gridSpacing 80.0" ~/Library/preferences/com.apple.finder.plist

killall Finder &>/dev/null

# Enable pam-watchid (sudo commands using the Apple Watch)
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/logicer16/pam-watchid/HEAD/install.sh)" -- enable
