---
# https://github.com/DavidAnson/markdownlint
# Set everything to default values, other than exceptions below
default: true

# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.40.0/doc/md013.md
MD013:
  # Number of characters
  line_length: 120
  # Number of characters for headings
  heading_line_length: 80
  # Number of characters for code blocks
  code_block_line_length: 120
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: true
  # Include headings
  headings: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false

# MD041/first-line-heading/first-line-h1 : First line in a file should be a top-level heading
# https://github.com/DavidAnson/markdownlint/blob/v0.40.0/doc/md041.md
MD041:
  # Allow content before first heading
  allow_preamble: false
  # RegExp for matching title in front matter
  front_matter_title: "^\\s*title\\s*[:=]"
  # Heading level
  level: 1
